unit U_Dados;

interface

uses
  windows, SysUtils, Classes, DB, DBClient, Provider, ImgList, Controls,
  Dialogs, JvPageList, DBXFirebird, DBXMySql, WideStrings, SqlExpr, Inifiles,
  SWSystem, Forms, Graphics, FMTBcd, RDprint, Biblioteca;

type
  TF_Dados = class(TDataModule)
    CDS_Fornecedor: TClientDataSet;
    DS_Fornecedor: TDataSource;
    SaveDialog: TSaveDialog;
    OpenDialog: TOpenDialog;
    Conexao: TSQLConnection;
    Q_Fornecedor: TSQLQuery;
    DSP_Fornecedor: TDataSetProvider;
    CDS_Nivel: TClientDataSet;
    DS_Nivel: TDataSource;
    Q_Nivel: TSQLQuery;
    DSP_Nivel: TDataSetProvider;
    Q_Nivelmodulo: TStringField;
    Q_Nivelnick: TStringField;
    CDS_Nivelmodulo: TStringField;
    CDS_Nivelnick: TStringField;
    CDS_Funcionarios: TClientDataSet;
    DS_Funcionarios: TDataSource;
    Q_Funcionarios: TSQLQuery;
    DSP_Funcionarios: TDataSetProvider;
    CDS_Bancos: TClientDataSet;
    DS_Bancos: TDataSource;
    Q_Bancos: TSQLQuery;
    DSP_Bancos: TDataSetProvider;
    CDS_Unidade: TClientDataSet;
    DS_Unidade: TDataSource;
    Q_Unidade: TSQLQuery;
    DSP_Unidade: TDataSetProvider;
    CDS_Clientes: TClientDataSet;
    DS_Clientes: TDataSource;
    Q_Clientes: TSQLQuery;
    DSP_Clientes: TDataSetProvider;
    Q_Rap: TSQLQuery;
    CDS_Livros: TClientDataSet;
    DS_Livros: TDataSource;
    Q_Livros: TSQLQuery;
    DSP_Livros: TDataSetProvider;
    CDS_Particular: TClientDataSet;
    DS_Particular: TDataSource;
    Q_Particular: TSQLQuery;
    DSP_Particular: TDataSetProvider;
    CDS_Produtos: TClientDataSet;
    DS_Produtos: TDataSource;
    Q_Produtos: TSQLQuery;
    DSP_Produtos: TDataSetProvider;
    CDS_Departamento: TClientDataSet;
    DS_Departamento: TDataSource;
    Q_Departamento: TSQLQuery;
    DSP_Departamento: TDataSetProvider;
    Q_Clientesid: TIntegerField;
    Q_Clientesnome: TStringField;
    Q_Clientesendereco: TStringField;
    Q_Clientesbairro: TStringField;
    Q_Clientescep: TStringField;
    Q_Clientescidade: TStringField;
    Q_Clientesestado: TStringField;
    Q_Clientesfone: TStringField;
    Q_Clientesfax: TStringField;
    Q_Clientescelular: TStringField;
    Q_Clientescpf: TStringField;
    Q_Clientesobs: TStringField;
    Q_Clientesmae: TStringField;
    Q_Clientesrg: TStringField;
    Q_Clientesorgao: TStringField;
    Q_Clientesnascimento: TDateField;
    Q_Clientesdesde: TDateField;
    Q_Clientescnpj: TStringField;
    Q_Clientessexo: TStringField;
    Q_Clientesprofissao: TStringField;
    Q_Clientesempresa: TStringField;
    Q_Clientesfone_empresa: TStringField;
    Q_Clientesrenda: TFloatField;
    Q_Clientesref1: TStringField;
    Q_Clientesref2: TStringField;
    Q_Clientesfone_ref1: TStringField;
    Q_Clientesfone_ref2: TStringField;
    Q_Clientesdata_cadastro: TDateField;
    Q_Clientesauditoria: TStringField;
    CDS_Clientesid: TIntegerField;
    CDS_Clientesnome: TStringField;
    CDS_Clientesendereco: TStringField;
    CDS_Clientesbairro: TStringField;
    CDS_Clientescep: TStringField;
    CDS_Clientescidade: TStringField;
    CDS_Clientesestado: TStringField;
    CDS_Clientesfone: TStringField;
    CDS_Clientesfax: TStringField;
    CDS_Clientescelular: TStringField;
    CDS_Clientescpf: TStringField;
    CDS_Clientesobs: TStringField;
    CDS_Clientesmae: TStringField;
    CDS_Clientesrg: TStringField;
    CDS_Clientesorgao: TStringField;
    CDS_Clientesnascimento: TDateField;
    CDS_Clientesdesde: TDateField;
    CDS_Clientescnpj: TStringField;
    CDS_Clientessexo: TStringField;
    CDS_Clientesprofissao: TStringField;
    CDS_Clientesempresa: TStringField;
    CDS_Clientesfone_empresa: TStringField;
    CDS_Clientesrenda: TFloatField;
    CDS_Clientesref1: TStringField;
    CDS_Clientesref2: TStringField;
    CDS_Clientesfone_ref1: TStringField;
    CDS_Clientesfone_ref2: TStringField;
    CDS_Clientesdata_cadastro: TDateField;
    CDS_Clientesauditoria: TStringField;
    Q_Funcionariosid: TIntegerField;
    Q_Funcionariosid_departamento: TIntegerField;
    Q_Funcionariosnome: TStringField;
    Q_Funcionarioscpf: TStringField;
    Q_Funcionarioscomissao: TFloatField;
    Q_Funcionariosendereco: TStringField;
    Q_Funcionariosbairro: TStringField;
    Q_Funcionarioscep: TStringField;
    Q_Funcionariosfone: TStringField;
    Q_Funcionarioscelular: TStringField;
    Q_Funcionarioscidade: TStringField;
    Q_Funcionariosestado: TStringField;
    Q_Funcionariostipo: TStringField;
    Q_Funcionariosnick: TStringField;
    Q_Funcionariossenha: TStringField;
    Q_Funcionariosacesso: TStringField;
    Q_Funcionariosauditoria: TStringField;
    CDS_Funcionariosid: TIntegerField;
    CDS_Funcionariosid_departamento: TIntegerField;
    CDS_Funcionariosnome: TStringField;
    CDS_Funcionarioscpf: TStringField;
    CDS_Funcionarioscomissao: TFloatField;
    CDS_Funcionariosendereco: TStringField;
    CDS_Funcionariosbairro: TStringField;
    CDS_Funcionarioscep: TStringField;
    CDS_Funcionariosfone: TStringField;
    CDS_Funcionarioscelular: TStringField;
    CDS_Funcionarioscidade: TStringField;
    CDS_Funcionariosestado: TStringField;
    CDS_Funcionariostipo: TStringField;
    CDS_Funcionariosnick: TStringField;
    CDS_Funcionariossenha: TStringField;
    CDS_Funcionariosacesso: TStringField;
    CDS_Funcionariosauditoria: TStringField;
    Q_Fornecedorid: TIntegerField;
    Q_Fornecedorrazao: TStringField;
    Q_Fornecedorfantasia: TStringField;
    Q_Fornecedorendereco: TStringField;
    Q_Fornecedorbairro: TStringField;
    Q_Fornecedorcep: TStringField;
    Q_Fornecedorcidade: TStringField;
    Q_Fornecedorestado: TStringField;
    Q_Fornecedorfone: TStringField;
    Q_Fornecedorfax: TStringField;
    Q_Fornecedorcelular: TStringField;
    Q_Fornecedorcontato: TStringField;
    Q_Fornecedorcnpj: TStringField;
    Q_Fornecedorinscricao_estadual: TStringField;
    Q_Fornecedorauditoria: TStringField;
    CDS_Fornecedorid: TIntegerField;
    CDS_Fornecedorrazao: TStringField;
    CDS_Fornecedorfantasia: TStringField;
    CDS_Fornecedorendereco: TStringField;
    CDS_Fornecedorbairro: TStringField;
    CDS_Fornecedorcep: TStringField;
    CDS_Fornecedorcidade: TStringField;
    CDS_Fornecedorestado: TStringField;
    CDS_Fornecedorfone: TStringField;
    CDS_Fornecedorfax: TStringField;
    CDS_Fornecedorcelular: TStringField;
    CDS_Fornecedorcontato: TStringField;
    CDS_Fornecedorcnpj: TStringField;
    CDS_Fornecedorinscricao_estadual: TStringField;
    CDS_Fornecedorauditoria: TStringField;
    Q_Unidadeid: TIntegerField;
    Q_Unidadedescricao: TStringField;
    CDS_Unidadeid: TIntegerField;
    CDS_Unidadedescricao: TStringField;
    Q_Livrosid: TIntegerField;
    Q_Livrosid_unidade: TIntegerField;
    Q_Livroscodigo: TStringField;
    Q_Livrosdescricao: TStringField;
    Q_Livrosreferencia: TStringField;
    Q_Livrosautor_marca: TStringField;
    Q_Livrospreco: TFloatField;
    Q_Livrosestoque: TIntegerField;
    Q_Livroslivro_material: TStringField;
    Q_Livrosisbn: TStringField;
    Q_Livroscodigo_anterior: TStringField;
    Q_Livroscodigo_interno: TStringField;
    Q_Livrosnome: TStringField;
    Q_Livrosdescricao_pdv: TStringField;
    Q_Livrostotalizador_parcial: TStringField;
    Q_Livrosiat: TStringField;
    Q_Livrosippt: TStringField;
    Q_Livrosncm: TStringField;
    Q_Livrostipo_item_sped: TStringField;
    Q_Livrostaxa_issqn: TFloatField;
    Q_Livrostaxa_icms: TFloatField;
    Q_Livroscst: TStringField;
    Q_Livroscsosn: TStringField;
    Q_Livrosecf_icms_st: TStringField;
    Q_Livroscodigo_balanca: TIntegerField;
    Q_Livrosdata_cadastro: TDateField;
    Q_Livrosauditoria: TStringField;
    CDS_Livrosid: TIntegerField;
    CDS_Livrosid_unidade: TIntegerField;
    CDS_Livroscodigo: TStringField;
    CDS_Livrosdescricao: TStringField;
    CDS_Livrosreferencia: TStringField;
    CDS_Livrosautor_marca: TStringField;
    CDS_Livrospreco: TFloatField;
    CDS_Livrosestoque: TIntegerField;
    CDS_Livroslivro_material: TStringField;
    CDS_Livrosisbn: TStringField;
    CDS_Livroscodigo_anterior: TStringField;
    CDS_Livroscodigo_interno: TStringField;
    CDS_Livrosnome: TStringField;
    CDS_Livrosdescricao_pdv: TStringField;
    CDS_Livrostotalizador_parcial: TStringField;
    CDS_Livrosiat: TStringField;
    CDS_Livrosippt: TStringField;
    CDS_Livrosncm: TStringField;
    CDS_Livrostipo_item_sped: TStringField;
    CDS_Livrostaxa_issqn: TFloatField;
    CDS_Livrostaxa_icms: TFloatField;
    CDS_Livroscst: TStringField;
    CDS_Livroscsosn: TStringField;
    CDS_Livrosecf_icms_st: TStringField;
    CDS_Livroscodigo_balanca: TIntegerField;
    CDS_Livrosdata_cadastro: TDateField;
    CDS_Livrosauditoria: TStringField;
    Q_Produtosid: TIntegerField;
    Q_Produtosid_unidade: TIntegerField;
    Q_Produtoscodigo: TStringField;
    Q_Produtosdescricao: TStringField;
    Q_Produtosreferencia: TStringField;
    Q_Produtosautor_marca: TStringField;
    Q_Produtospreco: TFloatField;
    Q_Produtosestoque: TIntegerField;
    Q_Produtoslivro_material: TStringField;
    Q_Produtosisbn: TStringField;
    Q_Produtoscodigo_anterior: TStringField;
    Q_Produtoscodigo_interno: TStringField;
    Q_Produtosnome: TStringField;
    Q_Produtosdescricao_pdv: TStringField;
    Q_Produtostotalizador_parcial: TStringField;
    Q_Produtosiat: TStringField;
    Q_Produtosippt: TStringField;
    Q_Produtosncm: TStringField;
    Q_Produtostipo_item_sped: TStringField;
    Q_Produtostaxa_issqn: TFloatField;
    Q_Produtostaxa_icms: TFloatField;
    Q_Produtoscst: TStringField;
    Q_Produtoscsosn: TStringField;
    Q_Produtosecf_icms_st: TStringField;
    Q_Produtoscodigo_balanca: TIntegerField;
    Q_Produtosdata_cadastro: TDateField;
    Q_Produtosauditoria: TStringField;
    CDS_Produtosid: TIntegerField;
    CDS_Produtosid_unidade: TIntegerField;
    CDS_Produtoscodigo: TStringField;
    CDS_Produtosdescricao: TStringField;
    CDS_Produtosreferencia: TStringField;
    CDS_Produtosautor_marca: TStringField;
    CDS_Produtospreco: TFloatField;
    CDS_Produtosestoque: TIntegerField;
    CDS_Produtoslivro_material: TStringField;
    CDS_Produtosisbn: TStringField;
    CDS_Produtoscodigo_anterior: TStringField;
    CDS_Produtoscodigo_interno: TStringField;
    CDS_Produtosnome: TStringField;
    CDS_Produtosdescricao_pdv: TStringField;
    CDS_Produtostotalizador_parcial: TStringField;
    CDS_Produtosiat: TStringField;
    CDS_Produtosippt: TStringField;
    CDS_Produtosncm: TStringField;
    CDS_Produtostipo_item_sped: TStringField;
    CDS_Produtostaxa_issqn: TFloatField;
    CDS_Produtostaxa_icms: TFloatField;
    CDS_Produtoscst: TStringField;
    CDS_Produtoscsosn: TStringField;
    CDS_Produtosecf_icms_st: TStringField;
    CDS_Produtoscodigo_balanca: TIntegerField;
    CDS_Produtosdata_cadastro: TDateField;
    CDS_Produtosauditoria: TStringField;
    Q_Particularid: TIntegerField;
    Q_Particularnome: TStringField;
    Q_Particularcnpj: TStringField;
    Q_Particularinscricao_estadual: TStringField;
    Q_Particularendereco: TStringField;
    Q_Particularbairro: TStringField;
    Q_Particularcidade: TStringField;
    Q_Particularestado: TStringField;
    Q_Particularcep: TStringField;
    Q_Particularfone: TStringField;
    Q_Particularfax: TStringField;
    Q_Particularcontato: TStringField;
    Q_Particularcelular: TStringField;
    Q_Particulardiretor: TStringField;
    Q_Particularaniversario: TStringField;
    Q_Particularauditoria: TStringField;
    CDS_Particularid: TIntegerField;
    CDS_Particularnome: TStringField;
    CDS_Particularcnpj: TStringField;
    CDS_Particularinscricao_estadual: TStringField;
    CDS_Particularendereco: TStringField;
    CDS_Particularbairro: TStringField;
    CDS_Particularcidade: TStringField;
    CDS_Particularestado: TStringField;
    CDS_Particularcep: TStringField;
    CDS_Particularfone: TStringField;
    CDS_Particularfax: TStringField;
    CDS_Particularcontato: TStringField;
    CDS_Particularcelular: TStringField;
    CDS_Particulardiretor: TStringField;
    CDS_Particularaniversario: TStringField;
    CDS_Particularauditoria: TStringField;
    Q_Bancosid: TIntegerField;
    Q_Bancoscc: TStringField;
    Q_Bancosbanco: TStringField;
    Q_Bancosagencia: TStringField;
    Q_Bancosendereco: TStringField;
    Q_Bancoscidade: TStringField;
    Q_Bancosestado: TStringField;
    Q_Bancoscep: TStringField;
    Q_Bancosfone: TStringField;
    Q_Bancosfax: TStringField;
    Q_Bancosgerente: TStringField;
    Q_Bancosbairro: TStringField;
    Q_Bancosauditoria: TStringField;
    CDS_Bancosid: TIntegerField;
    CDS_Bancoscc: TStringField;
    CDS_Bancosbanco: TStringField;
    CDS_Bancosagencia: TStringField;
    CDS_Bancosendereco: TStringField;
    CDS_Bancoscidade: TStringField;
    CDS_Bancosestado: TStringField;
    CDS_Bancoscep: TStringField;
    CDS_Bancosfone: TStringField;
    CDS_Bancosfax: TStringField;
    CDS_Bancosgerente: TStringField;
    CDS_Bancosbairro: TStringField;
    CDS_Bancosauditoria: TStringField;
    Q_Departamentoid: TIntegerField;
    Q_Departamentonome: TStringField;
    Q_Departamentogerente: TStringField;
    CDS_Departamentoid: TIntegerField;
    CDS_Departamentonome: TStringField;
    CDS_Departamentogerente: TStringField;
    CDS_Dorc: TClientDataSet;
    DS_Dorc: TDataSource;
    Q_Dorc: TSQLQuery;
    DSP_Dorc: TDataSetProvider;
    CDS_Corc: TClientDataSet;
    DS_Corc: TDataSource;
    Q_Corc: TSQLQuery;
    DSP_Corc: TDataSetProvider;
    Q_Corcid: TIntegerField;
    Q_Corcid_escola: TIntegerField;
    Q_Corccodigo_orcamento: TStringField;
    Q_Corcserie: TStringField;
    Q_Corcano: TStringField;
    Q_Corcvalor_total: TFloatField;
    Q_Corcaluno: TIntegerField;
    Q_Corcpedido: TStringField;
    Q_Corcauditoria: TStringField;
    CDS_Corcid: TIntegerField;
    CDS_Corcid_escola: TIntegerField;
    CDS_Corccodigo_orcamento: TStringField;
    CDS_Corcserie: TStringField;
    CDS_Corcano: TStringField;
    CDS_Corcvalor_total: TFloatField;
    CDS_Corcaluno: TIntegerField;
    CDS_Corcpedido: TStringField;
    CDS_Corcauditoria: TStringField;
    Q_Dorcid: TIntegerField;
    Q_Dorcid_produto: TIntegerField;
    Q_Dorcid_orcamento_cabecalho: TIntegerField;
    Q_Dorccodigobarra: TStringField;
    Q_Dorcdescricao: TStringField;
    Q_Dorcquantidade: TIntegerField;
    Q_Dorcvalor_total: TFloatField;
    Q_Dorcunidade: TStringField;
    Q_Dorcvalor_unitario: TFloatField;
    Q_Dorcauditoria: TStringField;
    CDS_Dorcid: TIntegerField;
    CDS_Dorcid_produto: TIntegerField;
    CDS_Dorcid_orcamento_cabecalho: TIntegerField;
    CDS_Dorccodigobarra: TStringField;
    CDS_Dorcdescricao: TStringField;
    CDS_Dorcquantidade: TIntegerField;
    CDS_Dorcvalor_total: TFloatField;
    CDS_Dorcunidade: TStringField;
    CDS_Dorcvalor_unitario: TFloatField;
    CDS_Dorcauditoria: TStringField;
    CDS_Dorcreferencia: TStringField;
    CDS_Dorcautor_marca: TStringField;
    Q_Dorclivro_material: TStringField;
    CDS_Dorclivro_material: TStringField;
    CDS_ProcuraProd: TClientDataSet;
    DS_ProcuraProd: TDataSource;
    Q_ProcuraProd: TSQLQuery;
    DSP_ProcuraProd: TDataSetProvider;
    Q_ProcuraProdid: TIntegerField;
    Q_ProcuraProdid_unidade: TIntegerField;
    Q_ProcuraProdcodigo: TStringField;
    Q_ProcuraProddescricao: TStringField;
    Q_ProcuraProdreferencia: TStringField;
    Q_ProcuraProdautor_marca: TStringField;
    Q_ProcuraProdpreco: TFloatField;
    Q_ProcuraProdestoque: TIntegerField;
    Q_ProcuraProdlivro_material: TStringField;
    Q_ProcuraProdisbn: TStringField;
    Q_ProcuraProdcodigo_anterior: TStringField;
    Q_ProcuraProdcodigo_interno: TStringField;
    Q_ProcuraProdnome: TStringField;
    Q_ProcuraProddescricao_pdv: TStringField;
    Q_ProcuraProdtotalizador_parcial: TStringField;
    Q_ProcuraProdiat: TStringField;
    Q_ProcuraProdippt: TStringField;
    Q_ProcuraProdncm: TStringField;
    Q_ProcuraProdtipo_item_sped: TStringField;
    Q_ProcuraProdtaxa_issqn: TFloatField;
    Q_ProcuraProdtaxa_icms: TFloatField;
    Q_ProcuraProdcst: TStringField;
    Q_ProcuraProdcsosn: TStringField;
    Q_ProcuraProdecf_icms_st: TStringField;
    Q_ProcuraProdcodigo_balanca: TIntegerField;
    Q_ProcuraProddata_cadastro: TDateField;
    Q_ProcuraProdauditoria: TStringField;
    CDS_ProcuraProdid: TIntegerField;
    CDS_ProcuraProdid_unidade: TIntegerField;
    CDS_ProcuraProdcodigo: TStringField;
    CDS_ProcuraProddescricao: TStringField;
    CDS_ProcuraProdreferencia: TStringField;
    CDS_ProcuraProdautor_marca: TStringField;
    CDS_ProcuraProdpreco: TFloatField;
    CDS_ProcuraProdestoque: TIntegerField;
    CDS_ProcuraProdlivro_material: TStringField;
    CDS_ProcuraProdisbn: TStringField;
    CDS_ProcuraProdcodigo_anterior: TStringField;
    CDS_ProcuraProdcodigo_interno: TStringField;
    CDS_ProcuraProdnome: TStringField;
    CDS_ProcuraProddescricao_pdv: TStringField;
    CDS_ProcuraProdtotalizador_parcial: TStringField;
    CDS_ProcuraProdiat: TStringField;
    CDS_ProcuraProdippt: TStringField;
    CDS_ProcuraProdncm: TStringField;
    CDS_ProcuraProdtipo_item_sped: TStringField;
    CDS_ProcuraProdtaxa_issqn: TFloatField;
    CDS_ProcuraProdtaxa_icms: TFloatField;
    CDS_ProcuraProdcst: TStringField;
    CDS_ProcuraProdcsosn: TStringField;
    CDS_ProcuraProdecf_icms_st: TStringField;
    CDS_ProcuraProdcodigo_balanca: TIntegerField;
    CDS_ProcuraProddata_cadastro: TDateField;
    CDS_ProcuraProdauditoria: TStringField;
    CDS_ProcuraProdunidade: TStringField;
    CDS_CSoma: TClientDataSet;
    DS_CSoma: TDataSource;
    Q_CSoma: TSQLQuery;
    DSP_CSoma: TDataSetProvider;
    CDS_DSoma: TClientDataSet;
    DS_DSoma: TDataSource;
    Q_DSoma: TSQLQuery;
    DSP_DSoma: TDataSetProvider;
    CDS_CNC: TClientDataSet;
    DS_CNC: TDataSource;
    Q_CNC: TSQLQuery;
    DSP_CNC: TDataSetProvider;
    CDS_DNC: TClientDataSet;
    DS_DNC: TDataSource;
    Q_DNC: TSQLQuery;
    DSP_DNC: TDataSetProvider;
    Q_CSomaid: TIntegerField;
    Q_CSomaminuta: TIntegerField;
    Q_CSomavendedor: TIntegerField;
    Q_CSomasomador: TIntegerField;
    Q_CSomahora: TStringField;
    Q_CSomatotal: TFloatField;
    Q_CSomaecf: TStringField;
    Q_CSomanome_cliente: TStringField;
    Q_CSomacpf_cnpj: TStringField;
    Q_CSomaauditoria: TStringField;
    CDS_CSomaid: TIntegerField;
    CDS_CSomaminuta: TIntegerField;
    CDS_CSomavendedor: TIntegerField;
    CDS_CSomasomador: TIntegerField;
    CDS_CSomahora: TStringField;
    CDS_CSomatotal: TFloatField;
    CDS_CSomaecf: TStringField;
    CDS_CSomanome_cliente: TStringField;
    CDS_CSomacpf_cnpj: TStringField;
    CDS_CSomaauditoria: TStringField;
    Q_DSomaid: TIntegerField;
    Q_DSomaid_produto: TIntegerField;
    Q_DSomaid_soma_cabecalho: TIntegerField;
    Q_DSomaminuta: TIntegerField;
    Q_DSomadescricao: TStringField;
    Q_DSomacodigo: TStringField;
    Q_DSomaquantidade: TIntegerField;
    Q_DSomavalor_total: TFloatField;
    Q_DSomaunidade: TStringField;
    Q_DSomavalor_unitario: TFloatField;
    Q_DSomalivro_material: TStringField;
    Q_DSomanota_credito: TStringField;
    Q_DSomaauditoria: TStringField;
    CDS_DSomaid: TIntegerField;
    CDS_DSomaid_produto: TIntegerField;
    CDS_DSomaid_soma_cabecalho: TIntegerField;
    CDS_DSomaminuta: TIntegerField;
    CDS_DSomadescricao: TStringField;
    CDS_DSomacodigo: TStringField;
    CDS_DSomaquantidade: TIntegerField;
    CDS_DSomavalor_total: TFloatField;
    CDS_DSomaunidade: TStringField;
    CDS_DSomavalor_unitario: TFloatField;
    CDS_DSomalivro_material: TStringField;
    CDS_DSomanota_credito: TStringField;
    CDS_DSomaauditoria: TStringField;
    Q_CNCid: TIntegerField;
    Q_CNCminuta: TIntegerField;
    Q_CNCsomador: TIntegerField;
    Q_CNCvendedor: TIntegerField;
    Q_CNCnome: TStringField;
    Q_CNCendereco: TStringField;
    Q_CNCfone: TStringField;
    Q_CNCbairro: TStringField;
    Q_CNCcep: TStringField;
    Q_CNCcidade: TStringField;
    Q_CNCecf: TStringField;
    Q_CNCbaixa: TStringField;
    Q_CNCobs: TStringField;
    CDS_CNCid: TIntegerField;
    CDS_CNCminuta: TIntegerField;
    CDS_CNCsomador: TIntegerField;
    CDS_CNCvendedor: TIntegerField;
    CDS_CNCnome: TStringField;
    CDS_CNCendereco: TStringField;
    CDS_CNCfone: TStringField;
    CDS_CNCbairro: TStringField;
    CDS_CNCcep: TStringField;
    CDS_CNCcidade: TStringField;
    CDS_CNCecf: TStringField;
    CDS_CNCbaixa: TStringField;
    CDS_CNCobs: TStringField;
    Q_DNCid: TIntegerField;
    Q_DNCid_produto: TIntegerField;
    Q_DNCid_nota_credito_cabecalho: TIntegerField;
    Q_DNCminuta: TIntegerField;
    Q_DNCcodigo: TStringField;
    Q_DNCdescricao: TStringField;
    Q_DNCquantidade: TIntegerField;
    Q_DNCvalor_unitario: TFloatField;
    Q_DNCvalor_total: TFloatField;
    Q_DNCbaixa: TStringField;
    CDS_DNCid: TIntegerField;
    CDS_DNCid_produto: TIntegerField;
    CDS_DNCid_nota_credito_cabecalho: TIntegerField;
    CDS_DNCminuta: TIntegerField;
    CDS_DNCcodigo: TStringField;
    CDS_DNCdescricao: TStringField;
    CDS_DNCquantidade: TIntegerField;
    CDS_DNCvalor_unitario: TFloatField;
    CDS_DNCvalor_total: TFloatField;
    CDS_DNCbaixa: TStringField;
    Q_CSomadata_soma: TDateField;
    CDS_CSomadata_soma: TDateField;
    Q_CNCdata_nc: TDateField;
    CDS_CNCdata_nc: TDateField;
    CDS_Minuta: TClientDataSet;
    CDS_Minutaminuta: TIntegerField;
    DS_Minuta: TDataSource;
    Q_Minuta: TSQLQuery;
    Q_Minutaminuta: TIntegerField;
    DSP_Minuta: TDataSetProvider;
    CDS_DSoma1: TClientDataSet;
    DS_DSoma1: TDataSource;
    Q_DSoma1: TSQLQuery;
    DSP_DSoma1: TDataSetProvider;
    Q_DSoma1id: TIntegerField;
    Q_DSoma1id_produto: TIntegerField;
    Q_DSoma1id_soma_cabecalho: TIntegerField;
    Q_DSoma1minuta: TIntegerField;
    Q_DSoma1descricao: TStringField;
    Q_DSoma1codigo: TStringField;
    Q_DSoma1quantidade: TIntegerField;
    Q_DSoma1valor_total: TFloatField;
    Q_DSoma1unidade: TStringField;
    Q_DSoma1valor_unitario: TFloatField;
    Q_DSoma1livro_material: TStringField;
    Q_DSoma1nota_credito: TStringField;
    Q_DSoma1auditoria: TStringField;
    CDS_DSoma1id: TIntegerField;
    CDS_DSoma1id_produto: TIntegerField;
    CDS_DSoma1id_soma_cabecalho: TIntegerField;
    CDS_DSoma1minuta: TIntegerField;
    CDS_DSoma1descricao: TStringField;
    CDS_DSoma1codigo: TStringField;
    CDS_DSoma1quantidade: TIntegerField;
    CDS_DSoma1valor_total: TFloatField;
    CDS_DSoma1unidade: TStringField;
    CDS_DSoma1valor_unitario: TFloatField;
    CDS_DSoma1livro_material: TStringField;
    CDS_DSoma1nota_credito: TStringField;
    CDS_DSoma1auditoria: TStringField;
    CDS_DSomareferencia: TStringField;
    CDS_DSomaautor_marca: TStringField;
    CDS_DNCautor: TStringField;
    CDS_Contas: TClientDataSet;
    DS_Contas: TDataSource;
    Q_Contas: TSQLQuery;
    DSP_Contas: TDataSetProvider;
    Q_Contasid: TIntegerField;
    Q_Contascodigo: TIntegerField;
    Q_Contasconta: TStringField;
    CDS_Contasid: TIntegerField;
    CDS_Contascodigo: TIntegerField;
    CDS_Contasconta: TStringField;
    CDS_APagar: TClientDataSet;
    DS_APagar: TDataSource;
    Q_APagar: TSQLQuery;
    DSP_APagar: TDataSetProvider;
    Q_APagarid: TIntegerField;
    Q_APagarid_banco: TIntegerField;
    Q_APagarid_fornecedor: TIntegerField;
    Q_APagarnumero_nf: TStringField;
    Q_APagartotal_nf: TFloatField;
    Q_APagarnumero_pedido: TStringField;
    Q_APagarpago: TStringField;
    Q_APagarjuro: TFloatField;
    Q_APagarmulta: TFloatField;
    Q_APagarvalor_pago: TFloatField;
    Q_APagarconta: TIntegerField;
    Q_APagarcheque: TStringField;
    Q_APagarduplicata: TStringField;
    Q_APagarxx: TStringField;
    Q_APagarnominal: TStringField;
    Q_APagartotal_produtos: TFloatField;
    Q_APagaremissao: TDateField;
    Q_APagarentrada: TDateField;
    Q_APagarvencimento: TDateField;
    Q_APagarpagamento: TDateField;
    Q_APagardata_cheque: TDateField;
    Q_APagarlancamento: TDateField;
    Q_APagarauditoria: TStringField;
    CDS_APagarid: TIntegerField;
    CDS_APagarid_banco: TIntegerField;
    CDS_APagarid_fornecedor: TIntegerField;
    CDS_APagarnumero_nf: TStringField;
    CDS_APagartotal_nf: TFloatField;
    CDS_APagarnumero_pedido: TStringField;
    CDS_APagarpago: TStringField;
    CDS_APagarjuro: TFloatField;
    CDS_APagarmulta: TFloatField;
    CDS_APagarvalor_pago: TFloatField;
    CDS_APagarconta: TIntegerField;
    CDS_APagarcheque: TStringField;
    CDS_APagarduplicata: TStringField;
    CDS_APagarxx: TStringField;
    CDS_APagarnominal: TStringField;
    CDS_APagartotal_produtos: TFloatField;
    CDS_APagaremissao: TDateField;
    CDS_APagarentrada: TDateField;
    CDS_APagarvencimento: TDateField;
    CDS_APagarpagamento: TDateField;
    CDS_APagardata_cheque: TDateField;
    CDS_APagarlancamento: TDateField;
    CDS_APagarauditoria: TStringField;
    CDS_APagarfornecedor: TStringField;
    Q_APagarhistorico: TStringField;
    CDS_APagarhistorico: TStringField;
    CDS_APagarbanco: TStringField;
    CDS_Rec: TClientDataSet;
    DS_Rec: TDataSource;
    Q_Rec: TSQLQuery;
    DSP_Rec: TDataSetProvider;
    Q_Recid: TIntegerField;
    Q_Recid_banco: TIntegerField;
    Q_Recid_cliente: TIntegerField;
    Q_Recnf_fatura: TStringField;
    Q_Recentrada_saida: TStringField;
    Q_Recemissao: TDateField;
    Q_Recvencimento: TDateField;
    Q_Recvalor: TFloatField;
    Q_Recdesconto_nota: TFloatField;
    Q_Rectotal_nota: TFloatField;
    Q_Recdata_recebimento: TDateField;
    Q_Rectaxa_juro: TFloatField;
    Q_Recjuro: TFloatField;
    Q_Rectaxa_multa: TFloatField;
    Q_Recmulta: TFloatField;
    Q_Rectaxa_desconto: TFloatField;
    Q_Recdesconto: TFloatField;
    Q_Recvalor_recebido: TFloatField;
    Q_Rectipo_recebimento: TStringField;
    Q_Recmes: TStringField;
    Q_Recano: TStringField;
    Q_Rectipo_cliente: TStringField;
    Q_Recauditoria: TStringField;
    CDS_Recid: TIntegerField;
    CDS_Recid_banco: TIntegerField;
    CDS_Recid_cliente: TIntegerField;
    CDS_Recnf_fatura: TStringField;
    CDS_Recentrada_saida: TStringField;
    CDS_Recemissao: TDateField;
    CDS_Recvencimento: TDateField;
    CDS_Recvalor: TFloatField;
    CDS_Recdesconto_nota: TFloatField;
    CDS_Rectotal_nota: TFloatField;
    CDS_Recdata_recebimento: TDateField;
    CDS_Rectaxa_juro: TFloatField;
    CDS_Recjuro: TFloatField;
    CDS_Rectaxa_multa: TFloatField;
    CDS_Recmulta: TFloatField;
    CDS_Rectaxa_desconto: TFloatField;
    CDS_Recdesconto: TFloatField;
    CDS_Recvalor_recebido: TFloatField;
    CDS_Rectipo_recebimento: TStringField;
    CDS_Recmes: TStringField;
    CDS_Recano: TStringField;
    CDS_Rectipo_cliente: TStringField;
    CDS_Recauditoria: TStringField;
    Q_Rechistorico: TStringField;
    CDS_Rechistorico: TStringField;
    CDS_Reccliente: TStringField;
    CDS_Recbanco: TStringField;
    CDS_ItensNF: TClientDataSet;
    DS_ItensNF: TDataSource;
    Q_ItensNF: TSQLQuery;
    DSP_ItensNF: TDataSetProvider;
    Q_NFEntrada: TSQLQuery;
    CDS_NFEntrada: TClientDataSet;
    DS_NFEntrada: TDataSource;
    DSP_NFEntrada: TDataSetProvider;
    Q_NFEntradaid: TIntegerField;
    Q_NFEntradaid_fornecedor: TIntegerField;
    Q_NFEntradanome_fornecedor: TStringField;
    Q_NFEntradacnpj_fornecedor: TStringField;
    Q_NFEntradanumero_nf: TStringField;
    Q_NFEntradadata_emissao: TDateField;
    Q_NFEntradadata_entrada: TDateField;
    Q_NFEntradatotal_nf: TFloatField;
    CDS_NFEntradaid: TIntegerField;
    CDS_NFEntradaid_fornecedor: TIntegerField;
    CDS_NFEntradanome_fornecedor: TStringField;
    CDS_NFEntradacnpj_fornecedor: TStringField;
    CDS_NFEntradanumero_nf: TStringField;
    CDS_NFEntradadata_emissao: TDateField;
    CDS_NFEntradadata_entrada: TDateField;
    CDS_NFEntradatotal_nf: TFloatField;
    Q_ItensNFid: TIntegerField;
    Q_ItensNFid_produto: TIntegerField;
    Q_ItensNFid_nf_entrada_cabecalho: TIntegerField;
    Q_ItensNFcodigo: TStringField;
    Q_ItensNFdescricao: TStringField;
    Q_ItensNFquantidade: TIntegerField;
    Q_ItensNFvalor_unitario: TFloatField;
    Q_ItensNFvalor_total: TFloatField;
    Q_ItensNFunidade: TStringField;
    CDS_ItensNFid: TIntegerField;
    CDS_ItensNFid_produto: TIntegerField;
    CDS_ItensNFid_nf_entrada_cabecalho: TIntegerField;
    CDS_ItensNFcodigo: TStringField;
    CDS_ItensNFdescricao: TStringField;
    CDS_ItensNFquantidade: TIntegerField;
    CDS_ItensNFvalor_unitario: TFloatField;
    CDS_ItensNFvalor_total: TFloatField;
    CDS_ItensNFunidade: TStringField;
    CDS_Produtosunidade: TStringField;
    procedure DataModuleCreate(Sender: TObject);
    procedure CDS_UnidadeAfterPost(DataSet: TDataSet);
    procedure CDS_LivrosAfterPost(DataSet: TDataSet);
    procedure CDS_ProdutosAfterPost(DataSet: TDataSet);
    procedure CDS_DepartamentoAfterPost(DataSet: TDataSet);
    procedure CDS_DorcAfterPost(DataSet: TDataSet);
    procedure CDS_DorcBeforePost(DataSet: TDataSet);
    procedure CDS_DorccodigobarraChange(Sender: TField);
    procedure CDS_DSomaBeforePost(DataSet: TDataSet);
    procedure CDS_DNCAfterPost(DataSet: TDataSet);
    procedure CDS_DSomacodigoChange(Sender: TField);
    procedure CDS_ContasAfterPost(DataSet: TDataSet);
    procedure CDS_RecAfterInsert(DataSet: TDataSet);
    procedure CDS_ItensNFAfterPost(DataSet: TDataSet);
    procedure CDS_ItensNFBeforeEdit(DataSet: TDataSet);
    procedure CDS_ItensNFBeforeInsert(DataSet: TDataSet);
    procedure CDS_ItensNFBeforePost(DataSet: TDataSet);
  private
    { Private declarations }
  public
    RemoteAppPath, PathExporta: String;
    NomeEmpresa, EnderecoEmpresa: String;
    EmpresaID, QuantidadeECF: Integer;
  end;

var
  F_Dados: TF_Dados;
  quantid, quantid2: Integer;

implementation

uses UMenu, U_NFEntrada;
{$R *.dfm}

procedure TF_Dados.DataModuleCreate(Sender: TObject);
var
  ini: TIniFile;
  Banco: String;
begin
  try
    ini := TIniFile.Create(ExtractFilePath(Application.ExeName) + 'Parametros.ini');
    Banco := UpperCase(ini.ReadString('SGBD', 'BD', ''));
    RemoteAppPath := UpperCase(ini.ReadString('IMPORTA', 'REMOTEAPP', ''));
    NomeEmpresa := UpperCase(ini.ReadString('EMPRESA', 'NOME', ''));
    EnderecoEmpresa := UpperCase(ini.ReadString('EMPRESA', 'ENDERECO', ''));

    PathExporta := (ExtractFilePath(Application.ExeName) + 'Script\carga.txt');

    // Aqui você poderá carregar os dados de conexão de um arquivo INI, se desejar
    Conexao.Connected := True;
  finally
    ini.Free;
  end;
end;

procedure TF_Dados.CDS_ContasAfterPost(DataSet: TDataSet);
begin
  F_Dados.CDS_Contas.ApplyUpdates(0);
end;

procedure TF_Dados.CDS_DepartamentoAfterPost(DataSet: TDataSet);
begin
  if (CDS_Departamentonome.AsString <> '') then
  begin
    CDS_Departamento.ApplyUpdates(0);
  end;
  CDS_Departamento.Refresh;
  CDS_Departamento.Last;
end;

procedure TF_Dados.CDS_DorcAfterPost(DataSet: TDataSet);
begin
  CDS_Dorc.ApplyUpdates(0);
end;

procedure TF_Dados.CDS_DNCAfterPost(DataSet: TDataSet);
begin
  CDS_DNC.ApplyUpdates(0);
end;

procedure TF_Dados.CDS_DorcBeforePost(DataSet: TDataSet);
begin
  CDS_Dorcid_orcamento_cabecalho.AsInteger := CDS_Corcid.AsInteger;
  CDS_Dorcvalor_total.Value := CDS_Dorcvalor_unitario.Value * CDS_Dorcquantidade.Value;
end;

procedure TF_Dados.CDS_DorccodigobarraChange(Sender: TField);
begin
  If Length(CDS_Dorccodigobarra.AsString) = 13 then begin
    MyConsulta(F_Dados.Q_Produtos, 'select * from produto where codigo=' + chr(39) + CDS_Dorccodigobarra.AsString + chr(39));
    If Q_Produtoscodigo.AsString = '' then begin
      CDS_Dorc.Cancel;
      Application.MessageBox('Código não Cadastrado', 'Informação do Sistema', Mb_IconInformation);
    end
    else begin
      CDS_Dorcid_produto.AsInteger := F_Dados.Q_Produtosid.AsInteger;
      CDS_Dorcdescricao.AsString := F_Dados.Q_Produtosdescricao.AsString;
      CDS_Dorcvalor_unitario.AsString := F_Dados.Q_Produtospreco.AsString;
      CDS_Dorclivro_material.AsString := F_Dados.Q_Produtoslivro_material.AsString;
      // Exercício: Arrume uma maneira de gravar a descrição da unidade
      CDS_Dorcunidade.AsString := F_Dados.Q_Produtosid_unidade.AsString;
      CDS_Dorcauditoria.AsString := DateTimeToStr(Now);
    end;
  end;
end;

procedure TF_Dados.CDS_DSomaBeforePost(DataSet: TDataSet);
begin
  CDS_DSomaid_soma_cabecalho.AsInteger := CDS_CSomaid.AsInteger;
  CDS_DSomaminuta.AsInteger := CDS_CSomaminuta.AsInteger;
  CDS_DSomavalor_total.Value := CDS_DSomavalor_unitario.Value * CDS_DSomaquantidade.Value;
end;

procedure TF_Dados.CDS_DSomacodigoChange(Sender: TField);
begin
  If Length(CDS_DSomacodigo.AsString) = 13 then begin
    MyConsulta(F_Dados.Q_Produtos, 'select * from produto where codigo=' + chr(39) + CDS_DSomacodigo.AsString + chr(39));
    If Q_Produtos.RecordCount <= 0 then begin
      CDS_DSoma.Cancel;
      Application.MessageBox('Código não Cadastrado', 'Informação do Sistema', Mb_IconInformation);
    end
    else begin
      CDS_DSomaquantidade.Value := 1;
      CDS_DSomaid_produto.AsInteger := F_Dados.Q_Produtosid.AsInteger;
      CDS_DSomadescricao.AsString := F_Dados.Q_Produtosdescricao.AsString;
      CDS_DSomavalor_unitario.AsString := F_Dados.Q_Produtospreco.AsString;
      // Exercício: Arrume uma maneira de gravar a descrição da unidade
      CDS_DSomaunidade.AsString := F_Dados.Q_Produtosid_unidade.AsString;
      CDS_DSomaauditoria.AsString := DateTimeToStr(Now);
      CDS_DSoma.Post;
    end;
  end
  else begin
    Q_DSoma.Cancel;
  end;
end;

procedure TF_Dados.CDS_ItensNFAfterPost(DataSet: TDataSet);
begin
  //Exercício: tente implementar a atualização do estoque através de um tigger no banco de dados
  quantid2 := CDS_ItensNFquantidade.Value;
  if quantid <> quantid2 then
    quantid := quantid2 - quantid;
  F_Dados.Q_Produtos.Active := false;
  F_Dados.Q_Produtos.Sql.clear;
  F_Dados.Q_Produtos.Sql.add('select * from produto ');
  F_Dados.Q_Produtos.Sql.add('where codigo=' + chr(39) + CDS_ItensNFCodigo.AsString + chr(39));
  F_Dados.Q_Produtos.Active := True;
  F_Dados.CDS_Produtos.Close;
  F_Dados.CDS_Produtos.Open;
  F_Dados.CDS_Produtos.Edit;
  F_Dados.CDS_Produtosestoque.Value := F_Dados.CDS_Produtosestoque.Value + quantid;
  F_Dados.CDS_Produtos.Post;
  F_Dados.CDS_Produtos.ApplyUpdates(0);
  //
  quantid := 0;
  quantid2 := 0;
  //
  CDS_ItensNF.ApplyUpdates(0);
end;

procedure TF_Dados.CDS_ItensNFBeforeEdit(DataSet: TDataSet);
begin
  if CDS_ItensNFquantidade.Value < 0 then
    CDS_ItensNFquantidade.Value := 0;
  quantid := CDS_ItensNFquantidade.Value;
end;

procedure TF_Dados.CDS_ItensNFBeforeInsert(DataSet: TDataSet);
begin
  if CDS_ItensNFquantidade.Value < 0 then
    CDS_ItensNFquantidade.Value := 0;
  quantid := CDS_ItensNFquantidade.Value;
end;

procedure TF_Dados.CDS_ItensNFBeforePost(DataSet: TDataSet);
var
  tot: double;
begin
  if Assigned(F_NFEntrada) then
  begin
    if F_Dados.CDS_ItensNFCodigo.Value = '' then begin
      CDS_ItensNF.Cancel;
      Application.MessageBox('É Necessário Inserir o Código de Barra', 'Informação do Sistema', Mb_IconInformation);
    end
    else begin
      tot := CDS_ItensNFValor_Unitario.Value * CDS_ItensNFquantidade.Value;
      CDS_ItensNFid_nf_entrada_cabecalho.AsString := F_NFEntrada.Edit2.Text;
      CDS_ItensNFValor_Total.Value := tot;
    end;
  end;
end;

procedure TF_Dados.CDS_LivrosAfterPost(DataSet: TDataSet);
begin
  CDS_Livros.ApplyUpdates(0);
end;

procedure TF_Dados.CDS_ProdutosAfterPost(DataSet: TDataSet);
begin
  CDS_Produtos.ApplyUpdates(0);
end;

procedure TF_Dados.CDS_RecAfterInsert(DataSet: TDataSet);
begin
  CDS_Recvencimento.Value := date;
end;

procedure TF_Dados.CDS_UnidadeAfterPost(DataSet: TDataSet);
begin
  if (CDS_Unidadedescricao.AsString <> '') then
  begin
    CDS_Unidade.ApplyUpdates(0);
  end;
  CDS_Unidade.Refresh;
  CDS_Unidade.Last;
end;

end.
